spring:
  application:
    name: aggregator

application:
  pairs:
    - base: BTC
      quote: GBP

    - base: BTC
      quote: USD

    - base: ETH
      quote: GBP

exchange:
  bitstamp:
    name: Bitstamp
    apiUrl: https://www.bitstamp.net
    websocketUrl: wss://ws.bitstamp.net
